#+TITLE: [What]Yocto Project --> 编写 recipe
#+DATE: <2019-09-19 四> 
#+TAGS: yocto
#+LAYOUT: post 
#+CATEGORIES: linux, make, yocto
#+NAME: <yocto_write_recipe.org>
#+OPTIONS: ^:nil
#+OPTIONS: ^:{}

参考书籍:Embedded Linux System with the Yocto Project
- 书籍比实际的yocto版本要低，所以yocto的详细命令需要参考其[[https://www.yoctoproject.org/docs/][对应版本手册]]

运行环境:
- ubuntu18.04 amd64
- yocto 2.5.1

前面几章都是走马观花式的了解了一下 yocto 系统，可以看到其整个构建核心就是配置文件和 recipe。

其中配置文件仅仅是变量的赋值及修改，难点还是在于 recipe 的编写。

有了 recipe 的基础，接下来就会进入内核、BSP、APP 3大主题，这学习曲线还是有点绕……
#+BEGIN_HTML
<!--more-->
#+END_HTML
* recipe 的布局和惯例
recipe 的主要作用就是构建一个软件包，OpenEmbedded 的 wiki 提供了[[http://openembedded.org/wiki/Styleguide][recipe 编写风格说明]]。
** 文件名称
recipe 文件名称其实可以很灵活，但按照正规的命名规则分为两种方式：
*** 不通过版本控制的方式抓取的包
#+BEGIN_EXAMPLE
  <packagename>_<version>-<revision>.bb
  <packagename>_<version>-<revision>.bbappend
#+END_EXAMPLE
- packagename：recipe 要构建的软件包名，bitbake 会将其赋值给变量 =PN=
- version：软件包版本号，bitbake 会将其赋值给变量 =PV=
- revision：修订版本号，bitbake 会将其赋值给变量 =PR=
  
*注意：*
- 不要再在 packagename 中使用下划线了，而应该使用短横线
- version 和 revision 中不能再含有短横线了，而应该用英文句点分割
#+BEGIN_EXAMPLE
  avahi_0.6.31.bb
  linux-yocto_3.14.bb
  wps-supplicant_2.2.bb
#+END_EXAMPLE
*** 通过版本控制方式抓取的包
版本控制这里指的是像 git、svn、cvs 等这种工具，它们的命名规则为：
#+BEGIN_EXAMPLE
  <packagename>_<scm>.bb
#+END_EXAMPLE
packagename 的规则如前所述，scm 就是用 git、svn、cvs 替代。

在此基础之上，recipe 还需要将变量 =PV= 设置为如下格式：
#+BEGIN_EXAMPLE
  PV = "<version>+git${SRCREV}"
#+END_EXAMPLE
version 指的是 tag，而 SRCREV 值的是其修订版。

比如有文件 =meta-openembedded/meta-python/recipes-devtools/gyp/gyp_git.bb= ，这表明：
- 软件包名是 =gyp= ，并且是通过 git 进行版本控制

对应其内容为：
#+BEGIN_EXAMPLE
  DESCRIPTION = "GYP is a Meta-Build system: a build system that generates other build systems."
  HOMEPAGE = "https://gyp.gsrc.io/"
  LICENSE = "BSD-3-Clause"
  LIC_FILES_CHKSUM = "file://LICENSE;md5=ab828cb8ce4c62ee82945a11247b6bbd"
  SECTION = "devel"

  SRC_URI = "git://chromium.googlesource.com/external/gyp;protocol=https"
  SRCREV = "8bee09f4a57807136593ddc906b0b213c21f9014"

  S = "${WORKDIR}/git"
  PV = "0.1+git${SRCPV}"

  inherit setuptools3

  BBCLASSEXTEND = "native nativesdk"
#+END_EXAMPLE
** recipe 的内容结构
recipe 的内容可以分为多个小节来看，以 =meta/recipes-core/gettext/gettext_0.19.8.1.bb= 为例：
#+BEGIN_EXAMPLE
  # 对此 recipe（元数据）的说明
  SUMMARY = "Utilities and libraries for producing multi-lingual messages"
  DESCRIPTION = "GNU gettext is a set of tools that provides a framework to help other programs produce multi-lingual messages. \
  These tools include a set of conventions about how programs should be written to support message catalogs, a directory and file \
  naming organization for the message catalogs themselves, a runtime library supporting the retrieval of translated messages, and \
  a few stand-alone programs to massage in various ways the sets of translatable and already translated strings."
  HOMEPAGE = "http://www.gnu.org/software/gettext/gettext.html"

  # 包管理方式
  SECTION = "libs"

  # 授权
  LICENSE = "GPLv3+ & LGPL-2.1+"
  LIC_FILES_CHKSUM = "file://COPYING;md5=d32239bcb673463ab874e80d47fae504"

  # 继承说明
  inherit autotools texinfo pkgconfig

  # 构建说明
  DEPENDS = "gettext-native virtual/libiconv"
  DEPENDS_class-native = "gettext-minimal-native"
  PROVIDES = "virtual/libintl virtual/gettext"
  PROVIDES_class-native = "virtual/gettext-native"
  RCONFLICTS_${PN} = "proxy-libintl"
  SRC_URI = "${GNU_MIRROR}/gettext/gettext-${PV}.tar.gz \
       file://parallel.patch \
       file://add-with-bisonlocaledir.patch \
       file://cr-statement.c-timsort.h-fix-formatting-issues.patch \
       file://use-pkgconfig.patch \
  "

  SRC_URI[md5sum] = "97e034cf8ce5ba73a28ff6c3c0638092"
  SRC_URI[sha256sum] = "ff942af0e438ced4a8b0ea4b0b6e0d6d657157c5e2364de57baa279c1c125c43"


  EXTRA_OECONF += "--without-lispdir \
                   --disable-csharp \
                   --disable-libasprintf \
                   --disable-java \
                   --disable-native-java \
                   --disable-openmp \
                   --disable-acl \
                   --without-emacs \
                   --without-cvs \
                   --without-git \
                  "
  EXTRA_OECONF_append_class-target = " \
                   --with-bisonlocaledir=${datadir}/locale \
  "

  PACKAGECONFIG ??= "croco glib libxml"
  PACKAGECONFIG_class-native = ""
  PACKAGECONFIG_class-nativesdk = ""

  PACKAGECONFIG[croco] = "--without-included-libcroco,--with-included-libcroco,libcroco"
  PACKAGECONFIG[glib] = "--without-included-glib,--with-included-glib,glib-2.0"
  PACKAGECONFIG[libxml] = "--without-included-libxml,--with-included-libxml,libxml2"
  # Need paths here to avoid host contamination but this can cause RPATH warnings
  # or problems if $libdir isn't $prefix/lib.
  PACKAGECONFIG[libunistring] = "--with-libunistring-prefix=${STAGING_LIBDIR}/..,--with-included-libunistring,libunistring"
  PACKAGECONFIG[msgcat-curses] = "--with-libncurses-prefix=${STAGING_LIBDIR}/..,--disable-curses,ncurses,"

  acpaths = '-I ${S}/gettext-runtime/m4 \
             -I ${S}/gettext-tools/m4'

  do_install_append_libc-musl () {
    rm -f ${D}${libdir}/charset.alias
    rm -f ${D}${includedir}/libintl.h
    rm -f ${D}${libdir}/libintl.la
  }

  # 打包说明
  # these lack the .x behind the .so, but shouldn't be in the -dev package
  # Otherwise you get the following results:
  # 7.4M    glibc/images/ep93xx/Angstrom-console-image-glibc-ipk-2008.1-test-20080104-ep93xx.rootfs.tar.gz
  # 25M     uclibc/images/ep93xx/Angstrom-console-image-uclibc-ipk-2008.1-test-20080104-ep93xx.rootfs.tar.gz
  # because gettext depends on gettext-dev, which pulls in more -dev packages:
  # 15228   KiB /ep93xx/libstdc++-dev_4.2.2-r2_ep93xx.ipk
  # 1300    KiB /ep93xx/uclibc-dev_0.9.29-r8_ep93xx.ipk
  # 140     KiB /armv4t/gettext-dev_0.14.1-r6_armv4t.ipk
  # 4       KiB /ep93xx/libgcc-s-dev_4.2.2-r2_ep93xx.ipk

  PACKAGES =+ "libgettextlib libgettextsrc"
  FILES_libgettextlib = "${libdir}/libgettextlib-*.so*"
  FILES_libgettextsrc = "${libdir}/libgettextsrc-*.so*"

  PACKAGES =+ "gettext-runtime gettext-runtime-dev gettext-runtime-doc"

  FILES_${PN} += "${libdir}/${BPN}/*"

  # The its/Makefile.am has defined:
  # itsdir = $(pkgdatadir)$(PACKAGE_SUFFIX)/its
  # not itsdir = $(pkgdatadir), so use wildcard to match the version.
  FILES_${PN} += "${datadir}/${BPN}-*/*"

  FILES_gettext-runtime = "${bindir}/gettext \
                           ${bindir}/ngettext \
                           ${bindir}/envsubst \
                           ${bindir}/gettext.sh \
                           ${libdir}/libasprintf.so* \
                           ${libdir}/GNU.Gettext.dll \
                          "
  FILES_gettext-runtime-dev += "${libdir}/libasprintf.a \
                        ${includedir}/autosprintf.h \
                       "
  FILES_gettext-runtime-doc = "${mandir}/man1/gettext.* \
                               ${mandir}/man1/ngettext.* \
                               ${mandir}/man1/envsubst.* \
                               ${mandir}/man1/.* \
                               ${mandir}/man3/* \
                               ${docdir}/gettext/gettext.* \
                               ${docdir}/gettext/ngettext.* \
                               ${docdir}/gettext/envsubst.* \
                               ${docdir}/gettext/*.3.html \
                               ${datadir}/gettext/ABOUT-NLS \
                               ${docdir}/gettext/csharpdoc/* \
                               ${docdir}/libasprintf/autosprintf.html \
                               ${infodir}/autosprintf.info \
                              "

  # 重写任务
  do_install_append() {
      rm -f ${D}${libdir}/preloadable_libintl.so
  }

  do_install_append_class-native () {
    rm ${D}${datadir}/aclocal/*
    rm ${D}${datadir}/gettext/config.rpath
    rm ${D}${datadir}/gettext/po/Makefile.in.in
    rm ${D}${datadir}/gettext/po/remove-potcdate.sin

          create_wrapper ${D}${bindir}/msgfmt \
                  GETTEXTDATADIR="${STAGING_DATADIR_NATIVE}/gettext-0.19.8/"

  }

  # 扩展
  BBCLASSEXTEND = "native nativesdk"
#+END_EXAMPLE
*** 描述 recipe 的元数据
- SUMMARY：对软件包的简要描述，以一行描述且最多 80 个字符
- DESCRIPTION：对软件包的详细描述
- AUTHOR：描述作者的名字和 email 方式，可以列出多个作者。
#+BEGIN_EXAMPLE
  AUTHOR = "Santa Claus <santa@northpole.com>"
#+END_EXAMPLE
- HOMEPAGE：软件包的主站
- BUGTRACKER：追踪软件包 BUG 的站点
*** 软件包管理的元数据
这部分用于提供给包管理系统。
- SECTION：说明包的类型，包管理系统根据此变量来组织该包，可用的值有：
  + app,audio,base,devel,libs
- PRIORITY：描述此包可以作用于哪种系统，仅仅在 dpkg 和 opkg 包管理器下使用
  + standard：任何 linux 系统都适用的标准包
  + required：系统所必需的
  + optional：可选的
  + extra：可能会与系统的其他包相冲突
