* [What] Android --> base

** 编译
*** 编译过程中的问题
**** no such file: /home/xxx/.lunchrc
在使用 lunch 时,出现上面这个警告,解决步骤如下:
#+begin_example
source build/envsetup.sh
lunch
#+end_example
**** jdk版本太高
在ubuntu16.04中,jdk的最低版本都是1.8.0,而编译 android5.0.2需要1.7.x版本的,所以需要重新安装.
#+begin_example
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt update
sudo apt install openjdk-7-jdk
#+end_example
**** libstdc++.so.6: cannot open shared object file 
这是由于没有安装这个库而导致编译没有通过.
#+begin_example
sudo apt install lib32stdc++6
#+end_example
**** 编译到 libwebviewchromium.so 停止很长时间后发生错误
当编译过程卡在 =libwebviewchromium.so= 时, 有可能是正常现象, 也有可能会出错(需要等待大约1个多小时).
所以, *一定要在错误结果出现后再具体操作, 千万不要提前打断!*

当出现错误后, 一般是交换分区设置不足的问题造成的, 所以需要重新设定(建议10G).步骤如下:
#+begin_example
#新建分区
dd if=/dev/zero of=/opt/swap bs=1024 count=10240000
#将文件变成swap文件
mkswap /opt/swap
#启用swap文件
swapon /opt/swap
#每次开机时都启用
vim /etc/fstab
/opt/swap swap swap defaults 0 0
#+end_example
**** No command 'mmm' found....
在生成IDE文件时, 需要使用 =mmm= 命令, 此命令是编译包下的命令, 所以需要先执行 =source build/envsetup.sh= 
** 基础认知
*** 基本概念
Android驱动 = Linux驱动 + 封装

linux驱动通过JNI封装, 然后经过引擎形成一个统一访问层. 上层APP经过此层来达到统一访问底层的目的.
| java语言开发的APP |
| framework         |
| java与C接口层     |
| Linux驱动         |
| 底层              |

**** 开发APP的简易步骤
- 一个简单的APP布局以及控件的属性在 AS 中的 =content_main.xml= 文件中展现出来的。
- 如果想要控制某个小控件，在 =content_main.xml= 中选择控件类然后按下 =SHIFT + F11= 即可跳转到此类的操作说明页面
- 根据操作说明页面在 =MainActivity.java= 中对应的修改代码即可操作控件的显示以及控件之间的联系。
