#+TITLE: 危机感 --> 被淘汰的将来
#+DATE:  <2018-07-08 日> 
#+TAGS: feel
#+LAYOUT: post 
#+CATEGORIES: my world, 生活感悟, 心路历程
#+NAME: <myworld_life_feel_weedout.org>
#+OPTIONS: ^:nil 
#+OPTIONS: ^:{}

倘若现在还不持续性的学习与进步，在那即将到来的将来，或许我会被这个时代所淘汰......
#+BEGIN_HTML
<!--more-->
#+END_HTML
* 现状
今天老婆出差回来，给我讲了她所听到的目前教育现状。

她一个客户的儿子所在班级有80%的同学考上了成都479中学，而他儿子本人考上的是绵阳中学。嗯，真是一个优秀的班级。

可这不是重点，重点是他们这些同学 *在休息的这段时间就已经在开始上补习班、学习高中数学了！学习速度据说是贼快，学完立即做高考真题！*

其实这也不是第一次听到这种现象了，无论是小学还是初中，这些小朋友似乎都是在超前的学习且学习能力比我那个时代不知道强了多少。
* 思考
每次听到这种描述，我都在惊讶他们的学习能力同时，也在怀疑他们是否能够承受如此高强度的学习任务？

那么这就进一步需要思考:他们是被逼的吗？
如果是被逼的，我想无法一直这样死死坚持下去吧。 *但会不会有很多也是在随着自己兴趣在快乐的学习呢？*

读李笑来老师的[[https://book.douban.com/subject/27094706/][<财富自由之路>]] 中有一节这么说到:
#+BEGIN_EXAMPLE
  在过去，他们只是已经生活在另外一个世界，用知识改变命运，而在他们原来所处的那个世界里，
  他们已经"消失"了--在他们"消失"了的那个世界里，“知识无用”是一个必然实现的自证预言。
  可到了2013年，他们开始发朋友圈。他们的朋友圈就在那里，他们的整个世界别人都看得到，
  他们不会“消失”，他们的生活也在清楚地告诉别人：知识就是有用的，知识就是可以改变命运的
  --至少可以迅速变现。
#+END_EXAMPLE

如此，这些知识有用的心态会极大的激励现在的小学生、中学生，告诉他们学这些东西是有用的，是可以改变自己命运的。
更进一步，或许他们在知道这些道理之后，会根据自身条件和自我兴趣确定自己的终生奋斗目标。

虽然这些目标或许在以后的很多年会改变很多次，但其产生行动上的激励是极为有效的。

回想我读书那些年，我会觉得学这些东西没用，坚持到大学就解脱了。那是因为我根本看不到这些知识有用的人群的世界......

想到这里，结论就很明确了，这几乎是必然: *在今后的很多年里，优秀的毕业大学生比例会一直升高，甚至会以指数曲线的方式爆炸式的增长！*
* 我能做什么？
毫无疑问，这是一股洪流。极有可能在短短几年之后，这些大学生可以淘汰掉一些所谓有几年甚至十几年经验的老鸟。几年之后，我也才30多岁啊！

目前我所做的工作大部分内容都是低水平的重复建设，哪怕是加班也是无限的重复式的工作，只不过是 *看起来很努力而已！*
- 虽然最近半年多时间，我也在有意识的学习和积累，但这不够，远远不够！

倘若真这样持续几年之后，别说实现人生理想了，说不定工作都不保！人家比你年轻，能力还比你强，工资还要得比你低，不开你开谁？

所以，唯一的解决之道只有一条： *永不停止的，无限迭代的学习思考、进步、成长下去！*

我想，我是应该换个环境，去被那些牛人团队碾压碾压了......



