* [What]gnuradio --> base

[[https://gnuradio.org/doc/doxygen/index.html][手册]]

- [[#基本知识][基本知识]]
- [[#使用Python开发][使用Python开发]]

** 基本知识
*** 组成
gnuradio 是一个数据处理框架,通过图形块的方式来展示一个数据处理模块, 然后将这些模块连接起来就形成了流图(flowgraph).这些模块的各种参数最后都会以代码的形式传递给
python或c++.而模块之间的 *接口颜色则代表了不同的数据类型(通过 Help-Types 来查看).*

模块的参数在编辑时但未保存则为绿色.
*** 启动与调试
gunradio 使用命令 =gnuradio-companion=  *在命令行启动*!.
因为命令行会输出必要的调试信息!
*** 模块操作
- 流图最基本的有个 =Options= 块,用于对当前工程的一个总体设置.
  + 其中 =id= 选项用于命名整个工程的名字，其最终会生成一个与 =id= 一致的文件名和类名。
- 使用 =ctrl + f= 输入关键字便可查询其他模块, 对模块的更改可以使用 =ctrl + z= 来撤销更改.
-模块数据连接中, *当没有连接真实硬件时,需要使用 =throttle= 块,避免消耗过多的CPU.*
-关于模块的正常使用方式,依然是看它的说明文档!
  + 多个显示窗口的连接可以新建一个 =widget= 控件，然后其他显示窗口通过设置 =hint= 参数的方式挂载到控件上，比如 =tab@1= 代表将此窗口挂载到widget 的第二个tab上。
  + 需要注意的是，各个模块之间的信号采样率需要设置为一致，否则得到的信号不真实。
  + 使用模块 =Function Probe= 可以周期性的调用另外一个模块。
** 使用Python开发
当在图形界面使用 =generate= 功能时,便会生成和options中定义的ID名称一样的python文件.
**** 第一个简单的调用(如此的优雅)
#+BEGIN_SRC python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from gnuradio import gr
from gnuradio import audio
from gnuradio import analog

#gr.top_block 是gnuradio提供的基类
class my_top_block(gr.top_block):
    def __init__(self):
        gr.top_block.__init__(self)

        sample_rate = 32000
        ampl = 0.1

#信号源
        src0 = analog.sig_source_f(sample_rate, analog.GR_SIN_WAVE, 350, ampl)
        src1 = analog.sig_source_f(sample_rate, analog.GR_SIN_WAVE, 440, ampl)

#接收机
        dst = audio.sink(sample_rate, "")
#连接信号源和接收机
        self.connect(src0, (dst, 0))
        self.connect(src1, (dst, 1))

if __name__ == "__main":
    try:
        my_top_block().run()
    except [[KeyboardInterrupt]]:
        pass
#+END_SRC

**** 先使用界面构建,然后再修改代码
可以先在UI下构建基本工程,然后再去修改源码.需要注意的是, 如果再次修改了UI,那么源码会被再次更新.
对应的办法是将此 *文件复制一份再修改*, 然后使用命令行启动代码.
**** 块操作
gnuradio 使用 gr_modtool 来开发和管理模块(module).而块(block)则是存放在module中的.

块分为如下几类:
1. synchronous(1:1), 同步操作,也就是输入的数据数量与输出的数据数量一样多
2. decimation(N:1), 抽取操作,输入的数据量是输出的数据量的整倍数
3. interpolation(1:M),插值操作,输出的数据量是输入数据量的整数倍
4. general/basic(N:M),输入和输出之间没有固定的联系
***** gr_modtool 操作
- =gr_modtool help= 调用帮助说明
- =gr_modtool newmod <modname>= 创建一个新的模块, 模块中的 python,grc 文件夹需要关注
- =gr_modtool add -t <type> -l python= 创建一个 python 模块,根据向导即可.然后会在 python,grc 文件夹下生成以测试为目的的 qa 文件, 块文件, 与GRC连接的xml文件,以及更新CMakeLists.txt文件.

在选择块文件时, 需要规范文件后缀,后缀以输入输出数据类型而定.比如 multiply_py_ff , ff 代表输入为浮点,输出也为浮点.
***** 编码操作
- 进入块文件,修改源码以指定输入输出类型(in_sig, out_sig),以及数据运算过程(work方法).
  + 数据类型使用 =numpy.int8= 这种对象,具体说明位于: [[https:docs.scipy.org/doc/numpy/user/basics.type.html?][numpy]]
- 单元测试
  + 单元测试的核心思想: 将测试代码视为一个黑盒, 为黑盒提供 *遍历* 输入, 然后对比输出与理论值是否符合.

在gnuradio中,进入qa_xx文件,然后修改 =test_001_t= 这类文件.

***** XML文件
XML文件位于 grc 文件夹中,编辑此文件最终会显示在UI选项上.

通过提供标记(tag)来达到UI与python交互的目的.
***** 安装block
首先进入到module的根目录,然后运行如下脚本:
#+begin_example
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig
#+end_example
** 使用c++开发
*** 创建
参考 python 开发流程，先使用 =gr_modtool nm <modename>= 创建新模块，然后使用 =gr_modtool add <blockName>= 创建新的块。
*** 编辑
c++的代码存在于 =lib= 文件夹中，查看源码可以发现依然是有两个函数需要修改，一个在构造函数用于提供数据类型，一个在 work 函数用于提供执行流程。

*根据所选块的类型不同，或许还需要修改函数 forecast 来表示输入和输出之间的数量关系* 。