#+TITLE: [What]goodBook --> 逻辑学导论

- [[#逻辑学的基本概念][第一章 逻辑学的基本概念]]
  + [[#什么是逻辑学][1.1什么是逻辑学]]
  + [[#命题与论证][1.2命题与论证]]

* 逻辑学的基本概念
** 什么是逻辑学
*逻辑学是研究用于区分正确推理与不正确推理的方法和原理的学问。*

简单的讲，通过学习逻辑学，可以区分思考问题、得出结论的方式是否正确，这样既可以避免自己坑自己也可以避免别人有意或无意的坑自己。

应用逻辑的方法和技术能够在可靠的推理与谬误的推理之间做出可信赖的区分。
** 命题与论证
在推理的过程中，我们建构和评价 *论证* ，而论证是由 *命题* 构成的。
*** 命题
*命题(proposition)是用陈述句来断定事情是或不是如此这般。*

为了评价一个论证，需要对在该论证中出现的命题有全面的理解。

- 命题可以被肯定或被否定。 *每一个命令的结果都是真或者假，没有第三种结果！*
#+begin_example
比如 "宇宙中其他星球上有生命存在" 这个命题，目前无法确定真假。但是这个命题一定是或真或假的。
#+end_example
- 如果一个句子没有 *断定(assert)* 任何东西，那么它就不是命题。
#+begin_example
"你知道如何下象棋吗？" ， "噢，我的天哪！" ， "快点！" 。 问题、命令和感叹都是非真且非假的。
#+end_example
- 命题没有固定的句子，只要语境一致即可。
#+begin_example
"莱斯利赢了这场选举" 和 "这场选举由莱斯利赢得" ，虽然是不同语句，但做出了相同的断定。
#+end_example
- 命题不依赖于任何语言，不同的语言可以表达同一个命题。
- 命题(proposition)和陈述(statement)在逻辑学中通常意义相同。
- 同一语句在不同语境下可能是不同的命题。
#+begin_example
"美国最大的州曾经是一个独立的共和国" ， 对于 "德克萨斯州" 命题为真，对于 "阿拉斯加州" 命题为假。
#+end_example
- 命题可以是简单的一个命题，也可以是多个命题组合的一个大命题(合取或联言命题), *肯定一个合取命题，就等于分别肯定其所有分支命题* 。
#+begin_example
"亚马逊河流域制造了大约全球百分之二十的氧气，产生了其流域内的绝大部分降水，并且拥有许多未知的物种。" 

这个句子断定了三个命题的合取，分别是亚马逊河流域制造什么、产生什么和拥有什么。
#+end_example
- 也有一些复合命题并不断定其分支命题的真。 *析取(或选言)命题中的任何分支命题都没有得到断定。*
#+begin_example
“巡回法庭或者是有用的，或者是无用的。”

这个析取命题是真的，但其两个子命题中的其中一个肯定为假。
#+end_example
- 不断定其分支命题为真的复合命题是 *假言（或条件）* 命题。
#+begin_example
“如果上帝不存在，则有必要造出一个上帝。”

这里的两个分支命题也都没有被肯定，假言命题只是肯定了整个 “如果--那么”命题，
它既没有肯定“上帝不存在”，也没有肯定“有必要捏造一个上帝”，即使两个分支命题均为假，改条件命题也为真。
#+end_example
*** 论证
*论证是由命题构造的，它不需要包括异议或争论。*

*推论(inference)* 是一个能够将一组命题结合起来的过程，有些推论是 *保真的（或正确的）,* 有些不是。
逻辑学家分析这些命题簇，考擦这种推论过程的起始命题与结束命题以及它们之间的关系，这样的一个命题簇就构成了一个论证。
论证是逻辑学所关心的主要对象。

一个论证不只是一组命题的汇集，而是包含一定结构的命题簇，正是由于这种结构，才可以把捉或显示推论。

一个论证的 *结论* ，就是以论证中的其他命题为根据所得出的那个命题，这些被确定为真的子命题则是该论证的 *前提* 。

逻辑学家把关于论证的真假放在一边，焦点主要在于：
- 关注于该论证的 *形式(form)* ，以确定其是否是 *一种* 能产生保真结论的论证。
- 关注于论证的 *质(quality)* ，以确定该论证是否 *实际上* 产生了保真结论。
#+begin_example
我的理解是：逻辑学家关注的是关于结论的推理过程是否合理，通过合理的推理过程是否得到了正确的结论。
#+end_example

- 最简单的论证是只由一个前提和一个声称从该前提退出的结论所构成的。这种论证的前提与结论可以分别用两个不同的语句表述，也可以在同一句子中。
#+begin_example
“在地球上最先出现生命时没有人存在。因此，任何关于生命起源的陈述都应视为理论而非事实的陈述。”

“因为最近的进化史研究已经证明所有人都是从同一小群非洲祖先演变而来的，若仍相信种族间有极大差异，则如同相信地球是扁平的一样荒谬可笑”。
#+end_example
- 前提和结论出现的顺序也会有差异，但它并不能严格地决定论证的质。
#+begin_example
“当贝比鲁斯在纳温赛场上打出了他事业生涯的第700个全垒打的时候，一个会永远保持的记录诞生了。
它一定会被保持，首先是因为在以往历史上还没有人终身享有 the immortal Bambino 砖石；
其次，历史上只有另外两个棒球运动员打过超过300个的全垒打。” --1934年7月13日 <<纽约时报>>.

这是一个论证的两前提都居于结论之后，但却是一个看似可信实际结论为假的论证。
（汉克阿伦在1973年7月21日打到了他人生中的第700个全垒打。）

“凡法皆恶，乃因凡法皆为自由之违背。”

上面这句话，第一个是结论，第二个前提。
#+end_example
- 任何单个的命题都无法构成一个论证，因为论证是由一组命题构成的。但一些复合命题看起来却很像论证，需要注意区分。
#+begin_example
“如果我不喜欢人和蔼可亲，那么我就省去了喜欢他们的麻烦。”

第一个或第二个都没有得到断言，唯一得到断言的只是前者蕴含后者，并且两者都有可能为假，这是一个假言命题。
#+end_example
- 如果没有形成推论就没有结论被主张为真。
#+begin_example
“我不喜欢人和蔼可亲，因为这省去了喜欢他们的麻烦。”

第一个命题作为前提被断定，第二个命题作为由前提推导出的结论被断定。
#+end_example
- 并非任何具有一定结构的命题组都是论证。
#+begin_example
“在同一个世界上，大约有十亿人生活空前的富裕水平，也差不多有另外十亿人每天只有不到一美元的购买力而勉强度日。
世界上大多数最贫穷的人都营养不足，无法得到安全的饮用水和最基本的医疗服务，更没有办法送他们的子女上学接受教育。
根据联合国儿童基金会调查显示，每年有插过120万，即每天有3000儿童因与贫穷相关的缘故而死亡，这本是可以避免的。”

此报到都是陈述的事实，但没有推论，所以形不成论证。
#+end_example




