* [What]good book --> 说话的艺术
** 我也有话要说  ( powerby 李笑来)
*** 千万别装
注重一个事实: *群众的眼睛是雪亮的*!

无论是在台上还是在实际生活中,都要保持最真实的自己. 如果自己平时根本就不擅长做一件事, 却为了达到好的效果在最后关头装出来, 
那么到最后, 自己和观众都会觉得尴尬无比. *因为你不是在讲, 而是在演*.

所以, 就需要常常反问自己: *我到底是谁*?


*** 信任你的听众
*你的听众不是你的敌人*:听众花时间听你讲话, 最不希望你惊慌,紧张,手足无措...在不了解你之前,没有人对你抱有任何看法, 就算不是朋友,也起码不是敌人.
*你的听众不需要你故意取悦他们*,必要低估听众的智商, 心平气和的和听众交流和讨论.

*要相信听众*, 相信他们时有判断力的, 相信他们时有品位的, 相信他们时善良的, 相信他们是公正的, 相信他们拥有一切正面的品质.
*** 听众到底要什么?
听众想要听到的无非是拥有以下三个属性的东西(干货):
- 重要的
- 未知的
- 复杂的

*只有干货肯定是不行的, 正如纯粹的"营养餐"一定不好吃一样*.但是, 如若没有干货, 那你就是在忽悠, 你就是在装, 你就是不信任听众,
你必然遭到听众的唾弃--或早或晚, 别不服气, 这是宿命, 无法逃避.

*如果你的"干货"不够多, 那最好闭嘴, 把时间花在该花的地方--积累足够的干货*!
*** 你我皆凡人
如若你是个大名人, 大多数听众在你开口之前就已经"敞开了自己的心扉", 做好"聆听"一切的准备. 他们甚至可能早已准备好了纸笔, 生怕错过一点点的信息
-- 他们早已假定将要听到的一切都是重要的, 未知的, 复杂的...

但我们不是名人, 所以听众绝不可能"盲从", 他们并未一开始就"抗拒", 但是他们也没有从一开始就"欢迎", *必须认清这个残酷的现实!*.
*** 怎样开头?
开头并不是不重要, 但, *更重要的是内容*--只有一个精彩的开头, 而后乏善可陈, 多丢人阿!事实上, 乏善可陈的内容, 也不大可能有精彩的开头吧?

如果内容足够好, 三个字作为开头就可以了, "*大家好*..."
- 在台上用舒适而又挺立的姿势站好.
- 抬头, 露出灿烂的笑容.
- 缓慢环视四周(大约180度), 大约5 到 10 秒.
- 然后, 用恰当的声音说, "大家好..."

