* [What]good book --> 说话的艺术
** 我也有话要说  ( powerby 李笑来)
*** 千万别装
注重一个事实: *群众的眼睛是雪亮的*!

无论是在台上还是在实际生活中,都要保持最真实的自己. 如果自己平时根本就不擅长做一件事, 却为了达到好的效果在最后关头装出来, 
那么到最后, 自己和观众都会觉得尴尬无比. *因为你不是在讲, 而是在演*.

所以, 就需要常常反问自己: *我到底是谁*?

*** 信任你的听众
*你的听众不是你的敌人*:听众花时间听你讲话, 最不希望你惊慌,紧张,手足无措...在不了解你之前,没有人对你抱有任何看法, 就算不是朋友,也起码不是敌人.
*你的听众不需要你故意取悦他们*,必要低估听众的智商, 心平气和的和听众交流和讨论.

*要相信听众*, 相信他们时有判断力的, 相信他们时有品位的, 相信他们时善良的, 相信他们是公正的, 相信他们拥有一切正面的品质.
*** 听众到底要什么?
听众想要听到的无非是拥有以下三个属性的东西(干货):
- 重要的
- 未知的
- 复杂的

*只有干货肯定是不行的, 正如纯粹的"营养餐"一定不好吃一样*.但是, 如若没有干货, 那你就是在忽悠, 你就是在装, 你就是不信任听众,
你必然遭到听众的唾弃--或早或晚, 别不服气, 这是宿命, 无法逃避.

*如果你的"干货"不够多, 那最好闭嘴, 把时间花在该花的地方--积累足够的干货*!
*** 你我皆凡人
如若你是个大名人, 大多数听众在你开口之前就已经"敞开了自己的心扉", 做好"聆听"一切的准备. 他们甚至可能早已准备好了纸笔, 生怕错过一点点的信息
-- 他们早已假定将要听到的一切都是重要的, 未知的, 复杂的...

但我们不是名人, 所以听众绝不可能"盲从", 他们并未一开始就"抗拒", 但是他们也没有从一开始就"欢迎", *必须认清这个残酷的现实!*.
*** 怎样开头?
开头并不是不重要, 但, *更重要的是内容*--只有一个精彩的开头, 而后乏善可陈, 多丢人阿!事实上, 乏善可陈的内容, 也不大可能有精彩的开头吧?

如果内容足够好, 三个字作为开头就可以了, "*大家好*..."
- 在台上用舒适而又挺立的姿势站好.
- 抬头, 露出灿烂的笑容.
- 缓慢环视四周(大约180度), 大约5 到 10 秒.
- 然后, 用恰当的声音说, "大家好..."

*** 你想干什么?
一般来说, 当众讲话, 无非以下若干目的:
- 教学(teach) ; 更多出现在课堂上
- 告知(inform); 更多出现在广播中
- 探讨(discuss);通常在会议上
- 分享(share);往往是小组
- 鼓动(inspire);往往面对群众
*对于新手来说, 起点往往是分享*.

分享的意思是说, 讲者自己确信那东西是好地, 希望更多人知道.也就是说: *东西必须是你认为好的, 才有分享的必要*!

所以,在分享之前, 首先要问自己若干问题:
- 真的好么?
- 好在哪里?
- 为什么人们需要这种好?
- 拥有它有什么特别的地方?
- 没有它有什么特别的害处?
- 人们是不是低估了拥有它的好处?那我应该如何让人们意识到这点?
- 人们是不是低估了缺少它的害处?那我应该如何让人们意识到这点?
*** 什么元素最重要
*惊*, 就是最重要的元素.

如果你说了什么, 听众"当场就惊了", 那你就成功了一半.如果你已经做到"意料之外", 那,
还有另一半更难做到: 后面你所讲的一切必须是"情理之中" 的.

为了更好的制造"惊"的效果, 需要在开头, 中间和结尾都要突出. *但也不能太多*.

每个人, 每个时刻, 每个场合, 每个话题, 都有独特之处, 要花时间去考虑如何才能恰到好处且又合情合理地制造"惊"
的效果. 每个讲者都有不同的属性, 要根据自己的个性选择适当的方式. *这是一种能力, 能通过长期练习和实践慢慢积累的能力*.
*** 一次只说一件事
*一次只说一件事*, 这叫"主题鲜明".

任何一个话题, 足够深入的话, 是可以说很久的. 所以, *深入, 深入, 再深入*, 是把一件事说透, 说好, 说清楚, 说精彩的根本的技巧.

为了做到足够深入, 需要不断的反问自己:
- 我说的够清楚么? 够准确么? 是否需要对其中的概念, 范畴, 逻辑关系等等进行补充说明?是否会有一些听众对这些东西产生误解, 如若有这种可能, 我应该如何面对
- 有什么是所有听众都必然知道的?有什么是一些听众知道而另外一些听众不知道的?不知道的人大概占多少比例?
- 有什么东西是听众想不到的?我应该再什么样的地方, 把这些"意外"用什么样的方式, 什么样的措辞展现给听众?
- 要理解我正在说的这些事情, 有哪些事情是应该提前知道的? 而这些必须信息, 听众了解的究竟有多少?
- 有哪些事情是不重要的, 缺被大多数听众认为是重要的? 或者反过来, 有哪些事情是重要的却被大多数听众认为是不重要的?这些"错觉", "误解"是不是会造成很大的影响?如果是, 我又应该如何最直观地证明这种影响的存在?
- 这句话能不能更精彩一点? 这个例子是否足够恰当? 理由是否足够充分? 它们是否足够惊人?这个结论是否足够有意义? 该结论是否真能够改变听众的生活?
*** 你有99%的可能性被误解
作为个体的每一个听众, 各方面都是参差不齐的. 他可能并没有判断力, 却以为自己很是有一些判断力和判断资格;他可能在这一方面有品味,
不过很差的品味; 他很可能并不善良, 或者确实善良的, 然而却只不过是基于懦弱的那种善良; 他可能并不公正, 一生都活在双重标准之中,
宽于待己, 严于律人...... 他们中的一些人, 甚至可能拥有一些负面的品质.

最为可怕的, 是有很多听众从未认真审视过自己的" *选择性输入障碍*". 有很多时候, 讲者与听者之间的关系并不是相互的, 而是"你说你的, 我听我的".
到最后, 听者所听到的版本, 与讲者所讲的版本, 很可能相差十万八千里.

避免被误解的有效方法有这么几个:
- 尽量保持简单. 尽量保持逻辑关系简单明了.
- 避免引起听众的负面情绪
- 提前做功课, 做小范围内的沟通.
*** 更可能是你自己没说清楚
*要牢牢记住, 听众是陌生人.他们并不了解你, 所以要将事情说清楚!*

相应的对策是: *认真对待讲话之后与听众面对面的交流*.

首先要保持心态的平和, 而后, 认真记录听众的每一个反馈.其次, 不要急于为自己辩解,
甚至不要急于回答问题, 而是尝试着通过反向复述(您的意思是不是......)确定提问者的真正问题, 而后再认真回答.

不要怕"回答不出来", *新手就是新手, 需要磨炼, 这不丢人. 丢人的是不懂装懂 ,死撑却撑不住*.听众对这种人是没有任何耐心的,
换位思考以下吧, 换作是你, 可能会直接把这样的人归为某类, 从此再不理睬.

一切无法回答, 难以回答, 回答的不够清楚的问题, 都拿出纸笔记录下来, 以备提醒自己回去做足功课. 
当场纪录, 也会让听众明白你会认真考虑他们的问题.而后, 一定要告诉提问者, 你回去会马上想办法弄清楚, 并且会在第一时间向他反馈.
这样做不仅不丢人, 相反, 还可能会赢得尊重.
*** 使用你自己的语言
每个人在说话的时候, 措辞, 长短搭配, 语音语调的运用等等, 对每个人来说, 都是过往的语言使用所积淀下来的习惯, 人与人之间的不同, 可谓千差万别.

很多新手在准备演讲稿的时候, 往往忽略这一点, 把别人说过的话直接拿来就用,可是这是一厢情愿, 因为在台上, *基本上百分百会因为那并非属于自己的语言风格而产生结巴或者其他什么样的口误*.

平日里, 人们只关心自己是否表达顺畅.可是, *既然你要当众讲话, 就必须留意自己的语言风格*.

平时多留心一下, 就会发现自己的真实情况. 而经过这样的留心, 再看别人的句子或者语篇, 就很容易分辨你和人家之间的区别.

而当你需要复述什么东西的时候, 记得一定要用自己的语言重新创作,  *而不是"背"* .

对新手来说, 在演讲之前, *把要说的每句话都写下来*, 是很好的练习和实践的方法. 有些时候, 写出来的东西会吓你一跳:
脑子里以为正常的句子怎么会这么残疾? 实际上, 每个人都会在不知不觉中犯下这样那样的错误, 只不过, 平时没有人监督你, 
有错误也不见得有人指出罢了. 在台上, 你会如此, 然而, 会有人当场指出让你措手不及, 或者干脆懒得指出, 而后直接将你归入某类
--那是更可悲得结局. 所以, 全部写出来, 隔天自己仔细看一看, 这样简单得步骤, 可以让你免去很多尴尬.

*** 只说自己真正相信的话

