#+TITLE: [What]图解TCPIP_ip
#+DATE: <2018-07-29 日> 
#+TAGS: tcpip
#+LAYOUT: post
#+CATEGORIES: book,图解TCPIP(入门)
#+NAME: <book_图解TCPIP_chapter4_tcpip_ip.org>
#+OPTIONS: ^:nil
#+OPTIONS: ^:{}

TCP/IP的心脏是网络层，主要由IP(Internet Protocol) 和 ICMP(Internet Control Message Protocol)两个协议组成，先来学习IP.

主机: 配置有IP地址，但是不进行路由控制的设备

路由器: 配有IP地址又具有路由控制(数据转发)能力的设备

节点: 主机和路由器的统称
#+BEGIN_HTML
<!--more-->
#+END_HTML
* IP的作用
IP(IPv4,IPv6)相当于OSI参考模型的第三层--网络层，主要实现终端节点之间的通信，这种终端节点之间的通信也叫"点对点(end to end)通信"。
- 物理层与数据链路层的联合，仅能在一种数据链路节点之间进行包传递，而跨越多种数据链路，就需要借助网络层。

#+BEGIN_EXAMPLE
  如果我们只有行程表而没有车票，就无法搭乘交通工具到达目的地。反之如果除了车票其他什么都没有，恐怕也很难到达目的地。因为你不知道该坐什么车，也不知道在哪里换乘。因此只有两者兼备，既有某个区间的车票又有整个旅行的行程表，才能保证到达目的地。

  与之类似，计算机网络中也需要数据链路层和网络层才能实现向最终目标地址的通信。
#+END_EXAMPLE
* IP基础知识
IP大致分为三大作用模块，它们是IP寻址、路由、IP分包与组包。
** IP寻址
同一个数据链路的通信需要用到MAC地址，网络层也需要IP地址来区分各个连接上互联网的节点。
- 网桥或交换机线器等在物理层数据转发设备中，不需要设备IP地址，它们只负责数据部分转发不需要应对IP协议。
** 路由控制
路由控制(Routing)是指将 *分组数据* 发送到最终目标地址的功能.

当某个IP包到达路由器时，路由器首先查找其目标地址，从而再决定下一步应该将这个包发往哪个路由器。
当这个IP包达到那个路由器后，会再次经历查找下一目标地址的过程，并由该路由器转发给下一个被找到的路由器。
这个过程可能会反复多次，直到找到最终的目标地址将数据包发送给这个节点。

为了将数据包发给目标主机，所有主机都维护着一张路由控制表(Routing Table),该表记录IP数据在下一步应该发给哪个路由器，IP包将根据这个路由表在各个数据链路上传输。
** 数据链路的抽象化
对IP层来说，不论底层数据链路使用以太网还是无线LAN、PPP都将一视同仁.

不同的物理层MTU是不同的，IP对要发送的数据进行分片处理(IP Fragmentation)，接收端在依据序号进行组合。
** IP属于面向无连接型
为了简化协议及提高发送速度，在发包之前，不需要建立与对端目标地址之间的连接。








* IP地址基础知识
** 定义
IP地址由4个字节由点分隔组成，每个字节是无符号型。
- 理论上可以分配出43亿个IP组合，但由于某些IP有特殊用途，并且一些设备上有多块网卡，所以无法完成连接43亿台计算机。
** 组成
IP地址由"网络标识(网络地址)"和"主机标识(主机地址)"两部分组成。

比如 =192.168.128/24= 表示用24位来表示网络标识，其固定为 =192.168.128= ,剩下的为主机标识。
- 网络标识必须保证相互连接的每个段的地址不相重复，而相同段内相连的主机必须有相同的网络地址
- 相同段内的主机标识不允许重复出现
** 分类
IP地址分为 ABCD 类，根据网络地址区分。
- A类地址: 首位恒定为0，第1到第8位为网络标识: 0.0.0.0 ~ 127.0.0.0/8
  + 也就是其后24位都是主机地址，去除全0和全1的保留地址，说明每一个A类网络地址可以分配16777214个主机地址
- B类地址: 前两位恒定为 "10",第1位到第16位为网络标识: 128.0.0.0 ~ 191.255.0.0/16
  + 也就是其后16位都是主机地址，去除全0和全1的保留地址，说明每一个B类网络地址可以分配65534个主机地址
- C类地址: 前三位恒定为 "110",第1位到第24位是网络标识: 192.168.0.0 ~ 223.255.255.0/24
  + 也就是其后8位都是主机地址，去除全0和全1的保留地址，说明每一个C类网络地址可以分配254个主机地址
- D类地址: 前4位恒定为 "1110",第1位到第32位是网络标识: 224.0.0.0~239.255.255.255
  + 这种情况下没有主机地址了，常用于多播
** 广播地址
根据上面的地址分类，当主机地址为全1时，就代表广播地址，广播分为本地广播和直接广播两种。

- 本地广播:本地网络内的广播
- 直接广播:在不同网络之间的广播
** IP多播
多播用于将包发送给特定组内的所有主机， *由于其直接使用IP协议，因此也不存在可靠传输。*

多播使用的是D类地址，剩下的28位作为多播的组编号。
- 从224.0.0.0 ~ 224.0.0.255 不需要路由控制，在同一个链路内也能实现多播。而在范围外设置多播会给全网所有组成员发送多播的包。
- 所有的主机必须属于224.0.0.1的组，所有的路由器必须属于224.0.0.2的组。
** 子网掩码
子网掩码用于将ABC类地址进行细分，避免主机地址浪费。

子网掩码也由32位组成，对应网络地址的部分全部为1，对应主机地址的部分全部为0.

比如一个B类的IP地址: 172.20.100.0 ,其子网掩码为 255.255.255.192,这样其主机地址只剩下6位了。

最终其地址范围为: 172.20.100.0 ~ 172.20.100.63 ， 主机地址最多62位
  
** CIDR 与 VLSM
- 采用任意长度分割IP地址的网络标识和主机标识，这种方式叫做 CIDR(Classless Inter Domain Routing, 无类型域间选路)。
  + 利用CIDR可以将多个C类地址划分到一个较大的网络内。
- VLSM(可变长子网掩码) : 可以随机修改组织内各个部门的子网掩码长度的机制。
** 全局地址和私有地址
规定了私有网络的IP地址:
- A类 : 10.0.0.0 ~ 10.255.255.255
- B类 : 172.16.0.0 ~ 172.31.255.255
- C类 : 192.168.0.0 ~ 192.168.255.255

除此之外的IP地址为公网IP.

私有IP通过NAT技术访问互联网，这就缓解了IP分配资源紧张的问题。

