#+TITLE: [What]cmake_set
#+DATE:  <2018-01-25 Thu>
#+TAGS: cmake
#+LAYOUT: post 
#+CATEGORIES: linux, make, cmake
#+NAME: <linux_cmake_variable.org>
#+OPTIONS: ^:nil
#+OPTIONS: ^:{}

* 变量
变量在 cmake 中是一个最基本的存储单位。cmake 中也提供了[[https://cmake.org/cmake/help/v3.0/manual/cmake-variables.7.html][默认变量]] 具有特殊意义。
** 格式
- 变量名一般以大写或小写单词组成(大小写敏感)，单词和单词之间通过下划线连接。
- 变量的值一般是字符串或者数字
- 引用变量的内容使用 =${var_name}= 的方式，这点和linux下一致
  + 变量嵌套引用： =${outer_${inner_var}_variable}=
  + 在字符串中引用： =MESSAGE(STATUS "the value of variable is ${VAR_NAME}")=
- 设置变量最常用的命令有： =set, unset= , 以及在启动cmake时使用:
#+begin_example
cmake -D<val>=<value> ../
#+end_example
#+BEGIN_HTML
<!--more-->
#+END_HTML 
** 作用范围
变量的范围是动态的，具有以下范围：
*** 函数范围(Function Scope)
使用 =function()= 命令创建函数，在此函数内使用 =set()= 命令绑定的变量值，只在此函数和其子函数中可见。
*** 文件夹范围(Directory Scope)
*所谓的文件夹，这里指代的是含有 =CMakeLists.txt= 文件所在的文件夹。*

在构建系统最顶层具有 =CMakeLists.txt= 文件，然后在此文件中可以通过 =add_subdirectory()= 来包含子文件夹，子文件夹中也需要有 =CMakeLists.txt= 文件来构建。

在此层文件夹中给变量指定的值，会作用于此文件夹以及子文件夹(在函数中指定的值除外)。因为cmake在运行此层的 =CMakeLists.txt= 前，会将父文件中指定的变量以及拷贝到当前层。
*** 持续性缓存范围(Persistent Cache)
持续性缓存中保存的变量的值会存在于工程构建的多次运行中，也类似于相对于本工程的环境变量。
** 变量引用规则
cmake 中变量引用优先级依次是： 函数变量 -> 文件夹变量 -> 缓存变量 

如果按照上面顺序都没有找到的话，那此变量的值就是空字符串。
* set 命令
set 命令用于设置普通变量、缓存变量以及环境变量。 
- 可以给变量一次性设置多个值，这些值会存在一个列表中
- 当值为空时，它的作用就是 =unset()= 命令
- 当用双引号包围的值都是一个值，没有用双引号则是多个值
  + 比如 =set(var a b c d e)= 变量 var 有5个值，而 =set(var "a b c d e") 变量 var 只有一个值
** 设置普通变量
设置函数范围或文件夹范围的变量使用以下格式：
#+begin_example
set(<variable_name> <value1> [<value2>] ... [PARENT_SCOPE])
#+end_example
- 当使用 =PARENT_SCOPE= 选项时，这个变量作用范围将会在当前范围之上，到父范围中。
** 设置缓存变量
缓存变量可以给用户提供交互，用于设置该变量的值。

当使用 =ccmake= 或 =cmake-gui= 来构建时，便会出现配置界面。
#+begin_example
set(<variable_name> <value1> [<value2>] ... CACHE <type> <docstring> [FORCE])
#+end_example
- <type> 选项用于表明该变量的类型
  + BOOL :变量可以选择是 =ON/OFF=
  + FILEPATH :用于选择文件路径
  + PATH :用于选择文件夹路径
  + STRING :设置字符串，可以用户主动输入，或者在 =STRINGS= 缓存变量被设置时，用于选择
  + INTERNAL :使用此选项代表一个恒定值，与使用 =FORCE= 效果一致
- <docstring> 选项用于描述这个变量
- [FORCE] :选项用于设置一个恒定值

对于缓存变量还有一个命令可以将其设置为高级模式，高级模式的变量只有在 gui 设置显示高级模式时才显示：
#+begin_example
mark_as_advanced([CLEAR|FORCE] VAR [VAR2 ...])
#+end_example
- 如果选项为空，则新变量就会为设置为高级模式
- =CLEAR= : 取消一个变量的高级模式
- =FORCE= : 设置变量为高级模式

** 设置环境变量
设置当前用户环境变量：
#+begin_example
set(ENV{<variable_name>} <value1> [<value2>] ...)
#+end_example
* unset 命令
清空一个普通变量、缓存变量，使用下面格式：
#+begin_example
unset(<variable_name> [CACHE | PARENT_SCOPE])
#+end_example
- 当使用 =CACHE= 选项，代表清空一个缓存变量
- 当使用 =PARENT_SCOPE= 选项，代表清空一个父范围中的变量 

清空环境变量使用下面格式：
#+begin_example
unset(ENV{<variable_name>})
#+end_example




