* [What]Python --> base
*参考廖雪峰大神的网站*
** 语法
*** 基本格式
#+BEGIN_SRC python
#! /usr/bin/env python3   #指明python的运行路径
# -*- coding: utf-8 -*-   #指定使用utf8编码

a = 100
if a >= 0: #当语句以冒号结尾时,缩进的语句视为代码块
    print(a)
else:
    print(-a)
#+END_SRC
*** 输入和输出
**** 输出 -> print()
1. 括号内可以使用单引号或双引号包含的字符串,也可以使用逗号隔开多段字符串,逗号会被解释为空格.
2. 可以使用公式,从而直接输出公式结果.字符串与公式或变量也是使用逗号分隔
3. 使用百分号来索引格式化输出. =print("the number is %d" %5)=, 如果需要显示百分号,则在前面增加一个百分号转义.
**** 输入 -> input()
1. parameter = intput("please input your name:"), 可以输入任何字符串,内容存储在 parameter 中.

*** 条件判断
#+BEGIN_SRC python
if <条件判断1>:
    <执行1>
elif <条件判断2>:
    <执行2>
elif <条件判断3>:
    <执行3>
else:
    <执行4>

#+END_SRC
*** 循环
**** for
for x in y 循环依次把 y( list 或 tuple )中的每个元素取出来赋值给x,参与运算.
#+BEGIN_SRC python
#依次打印出 names 中的元素
names = ['Michael', 'Bob', "Tracy']
for name in names:
    print(name)
#+END_SRC
**** while 
while x 循环判断,只要x 为真则一直循环下去.
#+BEGIN_SRC python
sum = 0
n = 99
while n > 0:
    sum = sum + n
    n = n - 2
print(sum)
#+END_SRC
*** 函数
**** 函数的调用
函数的调用和 c/c++ 没什么不同,使用 =函数名(<参数列表>)= 的方式使用.

可以将函数名赋值给一个变量,相当于给函数起了一个别名:
#+BEGIN_SRC python
a = abs
a(-1)
#+END_SRC
**** 函数的定义
#+BEGIN_SRC python
#########
#普通函数
#########
def functionName(argc):

    #参数检查
    if not isinstance(argc, (int, float)):
        raise TypeError("bad operand type")
    
    if argc >= 0:
        return argc
    else:
        #当函数中没有 return 语句时,执行完毕返回的结果为 None
        return -argc

#########
#空函数
#########
def nop():
    pass

#########
#返回多个值,实际上返回的类型时 tuple
#########
import math
def move(x, y, step, angle = 0):#angle 是默认参数, 注意: 默认参数必须指向不变对象
    nx = x + step * math.cos(angle)
    ny = y - step * math.sin(angle)
    return nx, ny
#使用
x, y = move(100, 100, 60, math.pi / 6)

#########
# 可变参数函数
#########
#定义可变参数和定义一个list或tuple参数相比,仅仅在参数前面加了一个 *号.
#在函数内部,参数 numbers 接收到的是一个 tuple.调用该函数时,可以传入任意个参数,
#包括0个参数
def calc(*numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum
#使用
calc(1, 2)
calc()
#将list或tuple传入
nums = [1, 2, 3]
calc(*nums)

#########
# 关键字参数,允许传入0个或任意个含参数名的参数,这些关键字参数在函数内部自动组装位一个dict
#########
def person(name, age, **kw):
    print("name:", name, "age", age, "other", kw)
#使用
person("Michael", 30)
person("Bob", 35, city = "Beijing")

extra = {"city":"Beijing", "job": "Engineer"}
person("jack", 24, **extra)

#########
# 命名关键字参数,限定关键字参数的名字. 命令关键字参数必须传入参数名
#########
#限定只接收 city 和 job作为关键字参数
def person(name, age, *, city, job):
    print(name, age, city, job)

#如果函数定义中已经有了一个可变参数,后面跟着的命名关键字参数就不再需要一个特殊的分隔符了 *
def person(name, age, *args, city, job):
    print(name, age, args, city, job)

#关键字参数也可以具有默认值
def person(name, age, *, city = "Beijing", job):
    print(name, age, city, job)
    

#使用
person("Jack", 24, city = "Beijing", job = "Engineer")

####################
#参数组合
###################
#注意: 参数定义的顺序必须是:必选参数, 默认参数, 可变参数, 命名关键字参数, 关键字参数
def f1(a, b, c = 0, *args, **kw):
    print("a = ", a, "b = ", b, "c = ", c, "args = ", args, "kw = ", kw)

def f2(a, b, c = 0, *, d, **kw):
    print("a = ", a, "b = ", b, "c = ", c, "d = ", d, "kw = ", kw)

#使用
f1(1, 2)
f1(1, 2, c = 3)
f1(1, 2, 3, "a", "b")
f1(1, 2, 3, "a", "b", x = 99)
f2(1, 2, d = 99, ext = None)

args = (1, 2, 3, 4)
kw = {"d": 99, "x": "#"}
f1(*args, **kw)

args = (1, 2, 3)
kw = {"d":88, "x", "#"}
f2(*args, **kw)


#+END_SRC
**** 函数的递归
#+BEGIN_SRC python
#使用递归要注意避免栈溢出
def fact(n):
    if n == 1:
        return 1
    return n * fact(n - 1)

#使用尾递归优化的方式,避免栈溢出(在函数返回的时候,调用自身本身,并且 return 语句不能包含表达式
def fact_iter(num, product):
    if num == 1:
        return product
    return fact_iter(num - 1, num * product)

def fact(n):
    return fact_iter(n, 1)

#+END_SRC
*** 类
面向对象最重要的概念就是类和实例, 类是抽象的模板, 实例是根据类创建出来的一个具体的对象, 每个对象都拥有相同的方法, 但各自的数据可能不同.

*注意:* 在使用其他变量前,需要确定其已经被定义!
**** 类的定义
#+BEGIN_SRC python
#类名一般是大写开头的单词
#object 代表该类是从哪个类继承下来的, 如果没有合适的类,则使用 object 类
class Student(object):
    #self 代表实例本身, 在创建实例的时候,需要传入除 self 以外的参数
    def __init__(self, name, score):
        #以 __开头,代表是一个私有变量, python解释器将其翻译为了: self._Student_name
        self.__name = name
        self.__score = score
    #和普通函数相比,在类定义的函数只有一点不同,就是第一个参数永远是 self,并且调用时,
    #不用传递该参数.除此之外并没有声明不同,依然可以使用默认参数,可变参数,关键字参数和命名关键字参数
    def print_score(self):
        print("%s: %s" %(self.__name, self.__score))

#使用
bart = Student("Bart simpson", 59)
#可以自由地给一个实例变量绑定属性
bart.home = "sichuan"

#+END_SRC
**** 获取对象信息
#+BEGIN_SRC python
#使用 type() 函数来判断对象的类型
>> type(123)
<class 'int'>
>> type("str")
<class 'str'>
>> type(Node)
<type(Node) 'NoneType'>

#比较两个变量是否为同类型
>>> type(123) == type(456)
True
>>> type('abc') == type(123)
False
#比较一个对象是否是函数
>>> type(fn) == types.FunctionType

# 使用 isinstance() 来判断class的类型
# 假设继承关系: object -> Animal -> Dog -> Husky
>>> a = Animal()
>>> d = Dog()
>>> h = Husky()
>>> isinstance(h, Husky)
True
>>> isinstance(h, Dog)
True
>>> isinstance(h, Animal)
True
>>> isinstance(d, Husky)
False

#使用 dir() 获得一个对象的所有属性和方法
#+END_SRC
**** 实例属性和类属性
由于Python是动态语言, 根据类创建的实例可以 *任意绑定属性*.
给实例绑定属性的方法是通过实例变量, 或者通过 self 变量:
#+BEGIN_SRC python
class Student(object):
    def __init__(self, name):
        self.name = name

s = Student('Bob')
s.score = 90

#Student 类本身需要绑定一个属性,可以直接在class中定义属性,这种属性是类属性,归Student类所有
#但是类的所有实例都可以访问到
class Student(object):
    name = 'Student'

    
#+END_SRC

*** 模块
在python 中,一个 .py 文件就称为一个模块(Module).同时为了避免模块名冲突,还引入了按目录来组织模块的方法,
称为包(Package).外部引用的方式就是 <包名>.<模块名>.

同样的,也可以有多级目录,来层层包含模块.

*注意*:
1. 每一个包目录下面都会有一个 =__init__.py= 的文件,这个文件是必须存在的,否则Python就把这个目录当成普通目录,
而表示一个包. =__init__.py= 可以是空文件,也可以有Python代码,因为 =__init__.py= 本身就是一个模块, 而它的模块名就是包名.

2. 自己创建的模块不能与python自带的模块名称冲突
**** 使用模块
#+BEGIN_SRC python
#! /usr/bin/env python3
# -*- coding:utf-8 -*-

#模块的文档注释,任何模块代码的第一个字符串都被视为模块的文档注释
"a test module"
#指明模块的作者
__author__ = "kcmetercec"

#导入 "sys"模块
#在导入包下的模块时,通常使用 from <包名> import 模块名, 这样就可以直接使用
import sys

def test():
    args = sys.argv
    if len(args) == 1:
        print("Hello, world!")
    elif len(args) == 2:
        print("Hello, %s!" % args[1])
    else:
        print("Too many arguments!")

# 当直接运行模块时,会执行此函数,用于测试模块,而其他地方导入则不会执行
if __name__=="__main__":
    test()
            
#+END_SRC

***** 作用域
- 模块内正常的函数和变量名都是公开的,可以被外部直接引用
- 类似 =__xxx__= 这样的特殊变量,也可以被引用,但是有特殊用途
- 类似 =_xxx 或 __xxx= 这样的函数就是非公开的, *不应该* 被直接引用

**** 安装第三方模块
安装第三方模块,时通过包管理工具 pip 完成的.

默认情况下,python 解释器会搜索当前目录,所有已经安装的内置模块和第三方模块. 搜索路径在 =sys.path= 变量中.
要修改此变量,可以:
- 添加要搜索的目录. *这种方法是在运行时修改,运行结束后失效*.
#+BEGIN_SRC python
import sys
sys.path.append('/Users/michael/my_py_scripts')
- 设置环境变量 =PYTHONPATH=, 只需要添加自己的搜索路径即可
#+END_SRC
*** 单元测试
**** 基本概念
- 测试夹具(test fixture): 代表进行一个单元测试之前或之后进行的准备或清理工作.类似于c++中的构造和析构函数.
- 测试用例(test case): 代表对一个实际的单元进行测试的代码.
- 测试套件(test suite): 代表几个测试用例的集合, 也可以层层包含,用于连续执行多个用例.
- 测试运行器(test runner): 代表运行测试用例的组件.
**** 基本格式
#+BEGIN_SRC python
#! /usr/bin/env python3

#test.py
#载入 单元测试模块
import unittest

#继承自 unittest.TestCase
class TestStringMethods(unittest.TestCase):

    #各个测试用例都要以 test_ 开头, 以便可以自动执行它们
    def test_upper(self):
        self.assertEqual('foo'.upper(), 'FOO')
    def test_isupper(self):
        self.assertTrue('FOO'.isupper())
        self.assertFalse('Foo'.isupper())
    def test_split(self):
        s = 'hello world'
        self.assertEqual(s.split(), ['hello', 'world'])
        with self.assertRaises(TypeError):
            s.split(2)

if __name__ == '__main__':
    unittest.main()
#+END_SRC

- 运行时,使用 =python3 test.py -v= 可以看到各个测试用例的结果

** 技巧